name: Documentation website

on: push


jobs:

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    environment: Kubernetes
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: global npm dependencies
        run: npm install --global concurrently@7 tailwindcss@3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: jdevries3133
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup kube config
        run: mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

        # `make deploy` recursively calls into sub-project makefiles in order
        # to deploy each of them. This might become brittle with scale since
        # it's a monolithic command, and can be broken into separate CI/CD
        # steps or jobs if it becomes an issue
      - name: Deploy application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make deploy
